version: '3'

services:
  client:
    build:
      context: ./streams-client
      args:
        - REACT_APP_HOST_IP_ADDRESS=http://YOUR_HOST_IP:3001
    ports:
      - "3000:80"

  server:
    build: ./streams-server
    volumes:
      - json-data:/usr/src/app
    ports:
      - "3001:3001"

volumes:
  json-data:
    driver: local
