apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: server-backend
        image: docker9686/streams-server
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 3004
    targetPort: 3001
    
